# Disable ordering whole modules, no point in that...

# Should eventually expand to commented out below, but this is the important part as per actual data layout...
source-item-ordering = ["enum", "struct"]
#source-item-ordering = ["enum", "impl", "struct", "trait"]
